DROP TABLE IF EXISTS login;
  
CREATE TABLE login (
  email  VARCHAR(250) PRIMARY KEY,
  password VARCHAR(250) NOT NULL,
  role VARCHAR(250) DEFAULT NULL,
  isactive VARCHAR(5) DEFAULT NULL
);


DROP TABLE IF EXISTS ORG;
  
CREATE TABLE ORG (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  location VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS EMP;
  
CREATE TABLE EMP (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  orgId INT,
  
  CONSTRAINT FK_EMP_ORG FOREIGN KEY (orgId) REFERENCES ORG(id)
);



DROP TABLE IF EXISTS Asset;
  
CREATE TABLE Asset (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  orgId INT,
  empId INT,
  
  CONSTRAINT FK_ASSET_ORG FOREIGN KEY (orgId) REFERENCES ORG(id),
  CONSTRAINT FK_ASSET_EMP FOREIGN KEY (empId) REFERENCES EMP(id)
);




